### ISSUE TITLE
fix login system. ^^

### ISSUE THREAD

**Issue by neotje** [neotje/neohub#5]
mehh

**Comment by florisweb** [comment]
Hmmm, found a security bug?

**Comment by neotje** [comment]
The login feature in firebase changed.

error:

Login Failed
This domain (neo-web.nl) is not authorized to run this operation. Add it to the OAuth redirect domains list in the Firebase console -> Auth section -> Sign in method tab.

**Comment by neotje** [comment]
I needed to authorize neo-web.nl domain in the auth section.

**Comment by neotje** [comment]
> Hmmm, found a security bug?

**Comment by neotje** [comment]
> Hmmm, found a security bug?

More like a new security feature in firebase.
